# Generated by Django 5.2.3 on 2025-07-02 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal'), ('NEGOCIO', 'Negocio')], default='PERSONAL', max_length=10)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subcategorias', to='core.categoria')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'padre')},
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('MEDIO_PAGO', 'Medio de pago'), ('SERVICIO', 'Servicio / Proveedor'), ('OTRA', 'Otra')], default='MEDIO_PAGO', max_length=15)),
                ('fecha_corte', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('MXN', 'Peso MXN'), ('USD', 'Dólar USD')], default='MXN', max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recurrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodicidad', models.CharField(help_text='RRULE iCal (ej. FREQ=MONTHLY;BYMONTHDAY=10)', max_length=100)),
                ('proxima_fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('cuenta_servicio', models.ForeignKey(limit_choices_to={'tipo': 'SERVICIO'}, on_delete=django.db.models.deletion.RESTRICT, to='core.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('TRANSFERENCIA', 'Transferencia interna')], default='GASTO', max_length=13)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('es_personal', models.BooleanField(default=True)),
                ('moneda', models.CharField(choices=[('MXN', 'Peso MXN'), ('USD', 'Dólar USD')], default='MXN', max_length=3)),
                ('conciliado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacciones', to='core.categoria')),
                ('cuenta_servicio', models.ForeignKey(blank=True, help_text='Proveedor o servicio (Telcel, CFE…) si aplica', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transacciones_servicio', to='core.cuenta')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacciones_pago', to='core.cuenta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.OneToOneField(limit_choices_to={'tipo': 'TRANSFERENCIA'}, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_entrante', to='core.transaccion')),
                ('origen', models.OneToOneField(limit_choices_to={'tipo': 'TRANSFERENCIA'}, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_saliente', to='core.transaccion')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha'], name='core_transa_fecha_029dac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['categoria', 'es_personal'], name='core_transa_categor_aa935d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['medio_pago'], name='core_transa_medio_p_2302d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('origen', models.F('destino')), _negated=True), name='origen_destino_distintos'),
        ),
    ]
