# Generated by Django 5.2.3 on 2025-07-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_cuenta_recurrencia_transaccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='fecha_pago',
            new_name='fecha_limite_pago',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='periodicidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de crédito'), ('CUENTA_AHORRO', 'Cuenta de ahorro / débito'), ('SERVICIO', 'Servicio / Proveedor')], max_length=15),
        ),
        migrations.CreateModel(
            name='ReciboServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_corte', models.DateField()),
                ('fecha_limite_pago', models.DateField()),
                ('abono_servicio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rs_abono', to='core.transaccion')),
                ('cargo_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rs_cargo_pago', to='core.transaccion')),
                ('cargo_servicio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rs_cargo', to='core.transaccion')),
                ('cuenta_servicio', models.ForeignKey(limit_choices_to={'tipo': 'SERVICIO'}, on_delete=django.db.models.deletion.RESTRICT, to='core.cuenta')),
            ],
            options={
                'ordering': ['-fecha_corte'],
            },
        ),
    ]
