# Generated by Django 5.2.3 on 2025-07-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_fecha_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='periodos', to='core.cuenta')),
            ],
            options={
                'ordering': ['-fecha_corte'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoServicio',
            fields=[
                ('periodobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.periodobase')),
                ('monto_pronto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_pronto_pago', models.DateField(blank=True, null=True)),
            ],
            bases=('core.periodobase',),
        ),
        migrations.CreateModel(
            name='PeriodoTDC',
            fields=[
                ('periodobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.periodobase')),
                ('pago_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago_no_intereses', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            bases=('core.periodobase',),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='core.periodobase'),
        ),
    ]
