# Generated by Django 5.2.3 on 2025-07-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_periodobase_periodoservicio_periodotdc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='reciboservicio',
            name='cuenta_servicio',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'SERV'}, on_delete=django.db.models.deletion.RESTRICT, to='core.cuenta'),
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='cuenta_servicio',
            field=models.ForeignKey(limit_choices_to={'tipo__codigo': 'SERV'}, on_delete=django.db.models.deletion.RESTRICT, to='core.cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuentas', to='core.tipocuenta'),
        ),
    ]
