# Generated by Django 5.2.3 on 2025-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tipocuenta_alter_reciboservicio_cuenta_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciboservicio',
            name='abono_servicio',
        ),
        migrations.RemoveField(
            model_name='reciboservicio',
            name='cargo_pago',
        ),
        migrations.RemoveField(
            model_name='reciboservicio',
            name='cargo_servicio',
        ),
        migrations.RemoveField(
            model_name='reciboservicio',
            name='cuenta_servicio',
        ),
        migrations.RemoveIndex(
            model_name='transaccion',
            name='core_transa_categor_aa935d_idx',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='fecha_corte',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='fecha_limite_pago',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='limite_credito',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='periodicidad',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='tasa_interes',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='es_personal',
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['categoria'], name='core_transa_categor_e5a3bf_idx'),
        ),
        migrations.DeleteModel(
            name='ReciboServicio',
        ),
    ]
