# Generated by Django 5.2.3 on 2025-07-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reciboservicio_abono_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodobase',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='periodotdc',
            name='periodobase_ptr',
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TDC', 'Tarjeta de Crédito'), ('SERV', 'Servicio')], max_length=10)),
                ('fecha_corte', models.DateField()),
                ('fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pago_no_intereses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_pronto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_pronto_pago', models.DateField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='periodos', to='core.cuenta')),
            ],
            options={
                'ordering': ['-fecha_corte'],
            },
        ),
        migrations.DeleteModel(
            name='PeriodoServicio',
        ),
        migrations.DeleteModel(
            name='PeriodoBase',
        ),
        migrations.DeleteModel(
            name='PeriodoTDC',
        ),
    ]
