# Generated by Django 5.2.3 on 2025-07-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_periodobase_cuenta_remove_transaccion_periodo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocuenta',
            options={'verbose_name': 'tipo de cuenta', 'verbose_name_plural': 'tipos de cuenta'},
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='grupo',
            field=models.CharField(choices=[('DEB', 'Debito'), ('SER', 'Servicios'), ('CRE', 'Creditos')], default='DEB', max_length=3),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
