# Generated by Django 5.2.3 on 2025-07-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tipocuenta_options_tipocuenta_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='tipo',
            field=models.CharField(choices=[('TDC', 'Tarjeta de Crédito'), ('SERV', 'Servicio'), ('DEB', 'Débito'), ('EFE', 'Efectivo')], max_length=10),
        ),
    ]
