# Generated by Django 5.2.3 on 2025-07-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_periodo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='fecha_apertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='no_cliente',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='no_contrato',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='ref_comentario',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='referencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
