# Generated by Django 5.2.3 on 2025-07-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cuenta_fecha_apertura_cuenta_no_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='periodo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='periodo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
