# Generated by Django 5.2.3 on 2025-07-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_periodo_descripcion_periodo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_corte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
