# Generated by Django 5.2.4 on 2025-07-29 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_periodo_fecha_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='ajuste',
            field=models.BooleanField(default=False, help_text='Marca este movimiento como ajuste para evitar la creación automática del segundo asiento.'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='grupo_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
