# Generated by Django 5.2.4 on 2025-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaccion_ajuste_transaccion_grupo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('NEGOCIO', 'Negocio'), ('MIXTO', 'Mixto'), ('TERCEROS', 'Terceros')], default='PERSONAL', max_length=10),
        ),
    ]
