# Generated by Django 5.2.4 on 2025-07-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='dia_corte',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes en que cierra el periodo (1-31)', null=True),
        ),
    ]
