# Generated by Django 5.2.4 on 2025-07-29 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cuenta_dia_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='fecha_fin_periodo',
            field=models.DateField(blank=True, help_text='Fecha de fin del periodo (generalmente igual a fecha_corte)', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='core.periodo'),
        ),
    ]
