# Generated by Django 5.2.4 on 2025-07-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_periodo_fecha_fin_periodo_transaccion_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='generado',
            field=models.BooleanField(default=False, verbose_name='Estado de cuenta generado'),
        ),
    ]
