# Generated by Django 5.2.4 on 2025-07-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_periodo_estado_alter_periodo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
