# Generated by Django 5.2.4 on 2025-07-30 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_periodo_cerrado_periodo_cerrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoestadolog',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.periodo'),
        ),
    ]
