# Generated by Django 5.2.4 on 2025-07-30 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_periodoestadolog_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoestadolog',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.periodo'),
        ),
    ]
