# Generated by Django 5.2.4 on 2025-08-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_periodoestadolog_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocuenta',
            name='naturaleza',
            field=models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], default='DEUDORA', max_length=10),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='grupo',
            field=models.CharField(choices=[('DEB', 'Debito'), ('SER', 'Servicios/gastos/proveedores'), ('CRE', 'Creditos'), ('ING', 'Ingresos')], default='DEB', max_length=3),
        ),
    ]
