# Generated by Django 5.2.4 on 2025-08-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tipocuenta_naturaleza_alter_tipocuenta_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='usar_saldo_prev',
            field=models.BooleanField(default=True, verbose_name='Usar saldo anterior como saldo inicial'),
        ),
    ]
