# Generated by Django 5.2.4 on 2025-08-02 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_periodo_usar_saldo_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='periodo_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodo_siguiente', to='core.periodo'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='saldo_inicial_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo inicial manual'),
        ),
    ]
