# Generated by Django 5.2.4 on 2025-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_periodo_periodo_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Inicial'),
        ),
    ]
