# Generated by Django 5.2.4 on 2025-08-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_periodoestadolog_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='dia_corte',
        ),
    ]
