# Generated by Django 5.2.4 on 2025-08-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_cuenta_dia_corte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='activo',
        ),
    ]
