# Generated by Django 5.2.4 on 2025-08-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_cuenta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='naturaleza',
            field=models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], default='DEUDORA', help_text='Naturaleza contable de la cuenta', max_length=10),
        ),
    ]
