# Generated by Django 5.2.4 on 2025-08-04 21:28

from django.db import migrations


def migrate_naturaleza_forward(apps, schema_editor):
    """Transferir naturaleza de TipoCuenta a Cuenta"""
    Cuenta = apps.get_model('core', 'Cuenta')
    TipoCuenta = apps.get_model('core', 'TipoCuenta')
    
    # Transferir naturaleza de tipo a cada cuenta
    for cuenta in Cuenta.objects.all():
        if cuenta.tipo and cuenta.tipo.naturaleza:
            cuenta.naturaleza = cuenta.tipo.naturaleza
            cuenta.save(update_fields=['naturaleza'])
        else:
            # Si no hay tipo o naturaleza, usar DEUDORA por defecto
            cuenta.naturaleza = "DEUDORA"
            cuenta.save(update_fields=['naturaleza'])


def migrate_naturaleza_reverse(apps, schema_editor):
    """Revertir migración - restaurar naturaleza en TipoCuenta"""
    # No podemos revertir completamente porque perdemos información
    # Si hay múltiples cuentas del mismo tipo con diferentes naturalezas
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_naturaleza_to_cuenta'),
    ]

    operations = [
        migrations.RunPython(migrate_naturaleza_forward, migrate_naturaleza_reverse),
    ]
