# Generated by Django 5.2.4 on 2025-08-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_migrate_naturaleza_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocuenta',
            name='naturaleza',
        ),
    ]
