# Generated by Django 5.2.4 on 2025-08-05 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_naturaleza_from_tipocuenta'),
    ]

    operations = [
        # Agregar campos nuevos al modelo Transaccion
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_origen',
            field=models.ForeignKey(
                blank=True,
                help_text='Cuenta de donde sale el dinero',
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='transacciones_origen',
                to='core.cuenta'
            ),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_destino',
            field=models.ForeignKey(
                blank=True,
                help_text='Cuenta hacia donde va el dinero (solo transferencias)',
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='transacciones_destino',
                to='core.cuenta'
            ),
        ),
        # Hacer categoria opcional
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(
                blank=True,
                help_text='Categoría del gasto/ingreso',
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='transacciones',
                to='core.categoria'
            ),
        ),
        # Agregar índices nuevos
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['cuenta_origen'], name='core_transa_cuenta__origen_idx'),
        ),
    ]
