# Generated by Django 5.2.4 on 2025-08-05 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_v060_fields'),
    ]

    operations = [
        # Hacer campos legacy opcionales para compatibilidad con v0.6.0
        migrations.AlterField(
            model_name='transaccion',
            name='medio_pago',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='transacciones_pago',
                to='core.cuenta'
            ),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta_servicio',
            field=models.ForeignKey(
                blank=True,
                help_text='Proveedor o servicio (Telcel, CFE…) si aplica',
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='transacciones_servicio',
                to='core.cuenta'
            ),
        ),
    ]
