# Generated by Django 5.2.4 on 2025-08-05 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_make_legacy_fields_optional'),
    ]

    operations = [
        # Hacer campos legacy restantes opcionales
        migrations.AlterField(
            model_name='transaccion',
            name='ajuste',
            field=models.BooleanField(
                default=False,
                blank=True,
                null=True,
                help_text="Campo legacy - será eliminado en v0.7.0"
            ),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='grupo_uuid', 
            field=models.UUIDField(
                default=uuid.uuid4,
                blank=True,
                null=True,
                editable=False,
                help_text="Campo legacy - será eliminado en v0.7.0"
            ),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(
                max_length=13,
                blank=True,
                null=True,  
                help_text="Campo calculado automáticamente en v0.6.0"
            ),
        ),
    ]
