# Generated by Django 5.2.4 on 2025-08-09 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_make_all_legacy_fields_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('cleared', 'Liquidada'), ('reconciled', 'Conciliada'), ('verified', 'Verificada')], default='pending', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PartidaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(blank=True, decimal_places=2, help_text='Importe del debe', max_digits=12, null=True)),
                ('credito', models.DecimalField(blank=True, decimal_places=2, help_text='Importe del haber', max_digits=12, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(blank=True, max_length=13)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('grupo_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ajuste', models.BooleanField(default=False)),
                ('moneda', models.CharField(choices=[('MXN', 'Peso MXN'), ('USD', 'Dólar USD')], default='MXN', max_length=3)),
                ('conciliado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_transaccion_legacy',
            },
        ),
        migrations.RemoveConstraint(
            model_name='transferencia',
            name='origen_destino_distintos',
        ),
        migrations.RemoveIndex(
            model_name='transaccion',
            name='core_transa_medio_p_2302d1_idx',
        ),
        migrations.RenameIndex(
            model_name='transaccion',
            new_name='core_transa_cuenta__f5965e_idx',
            old_name='core_transa_cuenta__origen_idx',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='ajuste',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta_servicio',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='grupo_uuid',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='medio_pago',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('cleared', 'Liquidada'), ('reconciled', 'Conciliada'), ('verified', 'Verificada')], default='pending', help_text='Estado del ciclo de vida de la transacción', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto de la transacción (siempre positivo)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('TRANSFERENCIA', 'Transferencia')], default='GASTO', editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='destino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_entrante', to='core.transaccion'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='origen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_saliente', to='core.transaccion'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo'], name='core_transa_tipo_4eba06_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['estado'], name='core_transa_estado_8dbb19_idx'),
        ),
        migrations.AlterModelTable(
            name='transferencia',
            table='core_transferencia',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='transaccion_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asiento_contable', to='core.transaccion'),
        ),
        migrations.AddField(
            model_name='partidacontable',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.asientocontable'),
        ),
        migrations.AddField(
            model_name='partidacontable',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_contables', to='core.cuenta'),
        ),
        migrations.AddField(
            model_name='partidacontable',
            name='transaccion_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_generadas', to='core.transaccion'),
        ),
        migrations.AddField(
            model_name='transaccionlegacy',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='legacy_transacciones', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='transaccionlegacy',
            name='cuenta_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='legacy_servicios', to='core.cuenta'),
        ),
        migrations.AddField(
            model_name='transaccionlegacy',
            name='medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='legacy_pagos', to='core.cuenta'),
        ),
        migrations.AddField(
            model_name='transaccionlegacy',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_transacciones', to='core.periodo'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['fecha'], name='core_asient_fecha_c4a6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['estado'], name='core_asient_estado_a80661_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['transaccion_origen'], name='core_asient_transac_deb5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='partidacontable',
            index=models.Index(fields=['cuenta', 'asiento'], name='core_partid_cuenta__9387c6_idx'),
        ),
        migrations.AddIndex(
            model_name='partidacontable',
            index=models.Index(fields=['asiento', 'debito'], name='core_partid_asiento_741afc_idx'),
        ),
        migrations.AddIndex(
            model_name='partidacontable',
            index=models.Index(fields=['asiento', 'credito'], name='core_partid_asiento_2dbcf3_idx'),
        ),
    ]
