# Generated by Django 5.2.4 on 2025-08-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_asientocontable_partidacontable_transaccionlegacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_conciliacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se concilió la transacción', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='referencia_bancaria',
            field=models.CharField(blank=True, help_text='Referencia/ID del banco para matching automático', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='saldo_posterior',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo de la cuenta después de esta transacción', max_digits=12, null=True),
        ),
    ]
