# Generated by Django 5.2.4 on 2025-08-09 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_transaccion_fecha_conciliacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_conciliados', models.IntegerField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='core.cuenta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_posterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confianza_match', models.CharField(choices=[('EXACTA', 'Coincidencia Exacta (99%)'), ('ALTA', 'Alta Confianza (95%)'), ('MEDIA', 'Media Confianza (90%)'), ('BAJA', 'Baja Confianza (85%)'), ('MANUAL', 'Revisión Manual')], default='MANUAL', max_length=10)),
                ('conciliado', models.BooleanField(default=False)),
                ('fecha_conciliacion', models.DateTimeField(blank=True, null=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.importacionbancaria')),
                ('transaccion_conciliada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_bancario_match', to='core.transaccion')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha', 'monto'], name='core_movimi_fecha_250eda_idx'), models.Index(fields=['referencia'], name='core_movimi_referen_239cff_idx'), models.Index(fields=['conciliado'], name='core_movimi_concili_b3699c_idx')],
            },
        ),
    ]
