# Generated by Django 5.2.4 on 2025-08-10 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_importacionbancaria_movimientobancario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='referencia_bbva',
            field=models.TextField(blank=True, help_text='Descripción original del estado de cuenta BBVA'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='saldo_posterior_bbva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo reportado por BBVA después de esta transacción', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ImportacionBBVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/bbva/%Y/%m/')),
                ('numero_cuenta_detectado', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('SUBIDO', 'Archivo subido'), ('ANALIZADO', 'Análisis completado'), ('VALIDANDO', 'Validando con usuario'), ('PROCESANDO', 'Creando transacciones'), ('COMPLETADO', 'Importación completada'), ('ERROR', 'Error en proceso'), ('CANCELADO', 'Cancelado por usuario')], default='SUBIDO', max_length=12)),
                ('paso_actual', models.IntegerField(default=1)),
                ('total_pasos', models.IntegerField(default=6)),
                ('fecha_primer_movimiento', models.DateField(null=True)),
                ('fecha_ultimo_movimiento', models.DateField(null=True)),
                ('total_movimientos_archivo', models.IntegerField(default=0)),
                ('saldo_inicial_archivo', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('saldo_final_archivo', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('movimientos_nuevos', models.IntegerField(default=0)),
                ('movimientos_duplicados', models.IntegerField(default=0)),
                ('cuentas_creadas', models.IntegerField(default=0)),
                ('categorias_creadas', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('log_proceso', models.JSONField(blank=True, default=dict)),
                ('notas_usuario', models.TextField(blank=True)),
                ('cuenta_bbva', models.ForeignKey(help_text='Cuenta BBVA 5019 de tipo DÉBITO', on_delete=django.db.models.deletion.CASCADE, to='core.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación BBVA',
                'verbose_name_plural': 'Importaciones BBVA',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='transaccion',
            name='importacion_bbva',
            field=models.ForeignKey(blank=True, help_text='Importación BBVA que creó esta transacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_creadas', to='core.importacionbbva'),
        ),
        migrations.CreateModel(
            name='MovimientoBBVATemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_excel', models.IntegerField()),
                ('fecha_original', models.DateField()),
                ('descripcion_original', models.TextField()),
                ('cargo_original', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abono_original', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_gasto', models.BooleanField()),
                ('monto_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_detectado', models.CharField(blank=True, max_length=50)),
                ('categoria_sugerida', models.CharField(blank=True, max_length=100)),
                ('descripcion_limpia', models.CharField(blank=True, max_length=255)),
                ('cuenta_destino_sugerida', models.CharField(blank=True, max_length=100)),
                ('validado_por_usuario', models.BooleanField(default=False)),
                ('es_duplicado', models.BooleanField(default=False)),
                ('ignorar', models.BooleanField(default=False)),
                ('notas_usuario', models.TextField(blank=True)),
                ('categoria_confirmada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('cuenta_destino_confirmada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bbva_destino', to='core.cuenta')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_temporales', to='core.importacionbbva')),
                ('transaccion_creada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen_bbva', to='core.transaccion')),
                ('transaccion_existente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados_bbva', to='core.transaccion')),
            ],
            options={
                'ordering': ['fila_excel'],
                'unique_together': {('importacion', 'fila_excel')},
            },
        ),
    ]
