# Generated by Django 5.2.4 on 2025-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_importacionbbva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la categoría', max_length=200),
        ),
    ]
