# Generated by Django 5.2.4 on 2025-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='medio_pago',
            field=models.BooleanField(default=False, help_text='Indica si esta cuenta puede usarse como medio de pago'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='propietario',
            field=models.CharField(blank=True, help_text='Propietario de la cuenta (ej: ADS, empresa, etc.)', max_length=50),
        ),
    ]
