# Generated by Django 5.2.4 on 2025-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_cuenta_medio_pago_cuenta_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='ajuste',
            field=models.BooleanField(default=False, help_text='Si es True, crea solo 1 asiento contable sin contrapartida automática'),
        ),
    ]
